#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#| echo=FALSE
knitr::opts_chunk$set(error = FALSE, message = FALSE, warning = FALSE)
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#| echo=FALSE
library(tidyverse)
library(janitor)
library(openxlsx)
library(skimr)
library(caret)
library(glmnet)
library(pROC)
library(kableExtra)
library(readxl)

library(table1)

library(Matrix)
library(writexl)





#
#
#
#| eval=FALSE
215825094.mailchimpapp.com
acquaintpublicationsgroup.live
advsurgsci.org
analytical2025-chemistry.com
analytical-chemistry2025.com
analytical-symposium2024.com
analytix-congress2025.com
annalsofcasereports.org
anncaserepimages.info
anncrmijurnl.info
artpublication.org
asjsms.com
austinmedresearch.com
authpubattrib.info
bax1.online
bigmarker.com
bilpublishing.net
biomedgrid.org
biomedgridresearch.org
biomed-res.com
biomed-res.org
biomedresresearch.co
biomedresresearch.com
biomedresresearch.org
blindreveiw.com
bpic-expo2024.com
cancercases.org
cardiologyauctoresonline.com
casesportal.online
casetrials.org
catalysis-congress.com
catalysis-symposium2025.com
cjpu.org
clevermatrix.org
clinicalmedic.com
clinicalnetworks.org
clinicalpapers.org
clinresearchstudies.org
conferenceinvites.org
conferenceprofspeakers.com
conferencesinsight.org
conferencestalkglobal.org
confshare.org
crimsonpublisher.com
cyagenbiosci.com
datadiscoverhub.biz
datadiscoverhub.net
dataexplorerhub.net
dataexplorerhubs.biz
directivepubcations.com
directivepubcations.org
directivepubcltions.org
directivepublication.org
directivpublications.com
directvepubctions.com
directvepubctions.org
eclinicalsci.com
eclinmed.com
editorialboard10@gmail.com
editorialboard37@gmail.com
editorialboardb24@gmail.com
eebioj.org
endocrinologyauctoresonline.com
eurosasiaconferences.com
explorecasespub.com
fjopz.com
food-congress.com
fortuneloa.com
gblscientificguild.org
gcke-congress.top
globalconferencemeet.com
globalindexing.net
globalscientificmeetings.net
globalscientificmeetings.org
gloriamartinremedy6@gmail.com
gresearchhealth.com
gsb2025-scitechcongress.com
gsgforum.com
hrpublicationslv.com
hspcorporation.net
hspcprocess.net
ijcicr.org
ijcmcasereports-us.info
ijcmcasestudy-io.info
ijiset.com
ijowcmc.com
ijseas.com
impactexplorers.org
impactnavigator.biz
indexedjournals.co
indexscript.org
info.wiley.com
inovineconference.com
investigatorspace.com
irispublishers.org
jartificialintelligence.info
jbiomedsci.net
jbresonline.com
jcmiedl.com
jcmimagescasereports.com
jjgahhep.com
jjgastroenterology.info
joddmc.net
joeducation.net
joindeepc.com
jopsci.org
journalssurgery.info
journal-submission.com
j-scimedcentral.us
jscimedpro.com
jscimedsubmissions.com
jsmclinics.com
jsmsubmission.com
jsmsubmissions.org
juniperpublications.org
juniperpublishers.co
lambdaconferences.org
literaryresearch.org
mailer.openpubsphere.com
mailer.opensciencejournals.net
mailguild.info
mcjrnlsschlrsd.info
medcdmo.com
meddocsoajurnalss.org
medicalclinicalcasestudyreports.org
medicineauctores.com
medicinejournalshsoa.org
medischolars.com
medjrnlresearchelicit.com
medloa.com
medoaustinjournals.info
medsresearch.info
meetingsint.net
meetingsnews.com
meghaz-meetings.org
nissipetricia.reviewprocess@gmail.com
openimpactforges.net
openpubspheres.net
openpubspheres.org
opulentmeetings.org
peersciences.com
pepcon2024.com
polscientific.com
pol-scientific.com
precisionglobalcon.org
precisionglobalconferences.org
prowebinarplaner.com
przevents.org
przforum.org
ptechzoa.net
ptechzoa.org
ptzscience.org
pubintellects.com
pubintellects.net
pubknowledgehub.biz
pubknowledgehubs.com
pulsusconferencs.com
rachelwalker32100@gmail.com
resartmetastand.info
rescollabhub.com
resdatacite.info
resdatacollab.info
resdataguides.biz
resdataharbor.net
resdataharvest.org
resdatamethods.info
resdataplus.org
researcher102.com
researchers-forum.com
researchersmeet.com
researchexplore.org
researchfront.biz
researchfrontline.org
researchmatrices.net
researchmatrices.org
researchsynergize.biz
researchvanguards.biz
researchwaves.net
rhadconference.org
rowpapers.com
salientjourhub.com
scholarlinkage.net
scholarlyopenaccessjournals.org
sciarticles.biz
scichemj.org
sciensl.com
scientificresearch.uk
scijour.info
scijournalmedncfp.com
scimedarticles.com
scimedjrnlarchivehub.com
sin-chn.net
smjournalpublications.com
smsubmissions.com
speakersgathering.com
stemjournal.info
submitmanu.com
submitopen.org
submitpaper.info
submitresearchers.com
surgicalcase.info
techsummit25@gmail.com
theconferencemail.org
thetsgcongress.com
tsgcongress.org
ubigene.cn
ubigene.tech
unileon.es
unitedmeetings.co.uk
virtualevent.biz
vyyoma.com
wbickr-conference2024.com
wcdd-symposium.com
wcdwce2025.com
wcfn2024conference.com
wcfn-symposium2025.com
yourcharter.ru
#
#
#
